Users can view all post
zicli/newsletter-api pull request #8
Opened 2020-04-07 16:35 UTC by Tueloper

## What it does
Sets up graphql and adds getNewsletter options

## How to Test
Postman graphql query
request
```javascript
  query {
      getAllNewsletter{
	 id
         title
         headerImage
         excerpt
         slug
         author
        content
      }
 }
```
response
```json
{
  "data": {
    "getAllNewsletter": []
  }
}
```

## What's next
- user can view a single post

2020-04-07 16:35 UTC, Tueloper commented
![](https://github.trello.services/images/mini-trello-icon.png) [public can view all newsletters](https://trello.com/c/qoZEKlLX/14-public-can-view-all-newsletters)

2020-04-07 17:22 UTC, dchima requested changes
Good work. hope you can see how easy it is to write graphql queries. 

Add types `createdAt` and `updatedAt` to the Post type.
Also update `docs/api.md` with new request/response.

2020-04-07 17:27 UTC, dchima commented
@Tueloper 
in project

```bash
npm i graphql-iso-date
```

in `src/generated/resolvers.js`
```javascript
import { GraphQLDate } from 'graphql-iso-date';

const resolvers = {

  Date: GraphQLDate,
  Query: {},
};
```

in `src/generated/typeDefs.js`
```javascript
const typeDefs = gql`
  scalar Date

  type Post {
    createdAt: Date!
    updatedAt: Data!
  }
`;
```

2020-04-08 08:24 UTC, dchima approved these changes

2020-04-08 08:24 UTC, merged